apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    name: myapp
    type: front-end

spec:
  template:
    metadata:
    name: myapp-pod
    labels:
      name: myapp-pod
      app: myapp
      type: pod
    spec:
      containers:
        - image:  nginx:lastest
          name:  nginx
  replicas: 3
